version:          '3.7'

services:
  my-comments:
    image:        ${DOCKER_TAG_BASE_NAME}/my-comments
    build:
      context:    ./
      cache_from:
        - ${DOCKER_TAG_BASE_NAME}/my-comments
    volumes:
      - '.:/srv/app'
      # Persist node modules
      - '/srv/app/node_modules'
    ports:
      - "3000:3000"
    environment:
      ## Used to allow auto page reload after editing a file (depends on volume too)
      - CHOKIDAR_USEPOLLING=true
